Clean up the bootstrap admin for integration tests.
Sage-Bionetworks/BridgeServer2-infra pull request #51
Opened 2021-12-20 19:29 UTC by alxdarksage

The only properties we currently need are the email and then the synapse user ID. The additional bootstrap accounts are also not used any longer. I manually updated these fields in EBS to get security patches out, but they'll need to be managed here.

2021-12-20 22:40 UTC, DwayneJengSage approved these changes
One comment about using a string literal instead of SSM. Otherwise, looks good.

2021-12-20 22:40 UTC, DwayneJengSage commented on config/prod/bridgeserver2.yaml
> +  BootstrapAdminSynapseUserId: !ssm /bridgeserver2-prod/BootstrapAdminSynapseUserId
I don't think the Synapse User ID needs to go into SSM. We could just make it a string literal in this file.

2021-12-22 02:06 UTC, DwayneJengSage requested changes

2021-12-22 02:06 UTC, DwayneJengSage commented on templates/bridgeserver2.yaml
>      Type: String
Needs NoEcho: true

2021-12-22 16:57 UTC, alxdarksage commented on templates/bridgeserver2.yaml
>      Type: String
Added

2022-01-06 17:09 UTC, alxdarksage commented
Also, added back admin.email environment variable because this is referenced during bootstrapping.

2022-01-07 01:46 UTC, DwayneJengSage approved these changes

2022-01-07 18:24 UTC, merged