Trying this again because my branch of the infra project seemed to be far off from the current state of the repo.
Sage-Bionetworks/BridgeServer2-infra pull request #54
Opened 2022-03-29 18:13 UTC by alxdarksage

2022-03-29 19:49 UTC, DwayneJengSage requested changes
Need to make the same changes for ExporterSynapseAccessToken.

2022-03-29 19:50 UTC, DwayneJengSage reviewed
Also, do we want to delete SynapseApiKey as well?

2022-03-29 21:05 UTC, alxdarksage commented
Added ExporterSynapseAccessToken, holding off on removing *ApiKey fields until after this deploys successfully.

2022-03-30 00:02 UTC, DwayneJengSage approved these changes

2022-03-30 16:38 UTC, merged